### create user
POST http://localhost:9000/api/user/create
Content-Type: application/json

{
    "username" : "evalia",
    "email" : "evalia@gmail.com",
    "password" : "1qazxsw23edcvfr4!"
}


### read all user
GET http://localhost:9000/api/users/read
Content-Type: application/json
